### ISSUE TITLE
taz.de not workling

### ISSUE THREAD

**Issue by tuxinaut** [nhoening/ttrss-flattr#2]
Firstly thanks for this good plugin

Unfortunately the plugin do not work with http://taz.de

The decodes link for the api request is the following

``` bash
http://www.taz.de/Textiler-Schutz-vor-Drohnen/!114022/
```

but the url with there the thing listed in flattr is the following

``` bash
http://www.taz.de/!114022/
```

It would be great to flattr http://taz.de with your plugin :)

**Comment by nhoening** [comment]
Yeah, I think that is a problem because taz uses different URLs to identify things on Flattr than they display put in their RSS feed. Both lead the browser to the same article, but to my plugin, they are different. 

I believe we're still in an early phase of the Flattr technology. In the README I hint at changes they made and maybe  the plugin could be updated and then such issues would stop being there. SAlas, I lack time at the moment to understand if that is so.

In the meantime, taz.de displays a Flattr button under each article. That's what I use. But I don't read taz.de in tt-rss. If they show the button in the feed, you're fine here, otherwise you need to open the article, so you need one click more for now...

**Comment by tuxinaut** [comment]
> I believe we're still in an early phase of the Flattr technology

Not anymore :smile:
